dev-init:
	terraform init -input=false -reconfigure

dev-plan:
	terraform plan

dev-deploy:
	terraform apply --auto-approve

dev-destroy:
	terraform destroy --auto-approve

dev-refresh:
	terraform refresh

dev-validate:
	terraform validate